pydiverse/pydiverse.pipedag

.github/workflows/ci.yml
.github/workflows/resources/docker_compose_ready.sh
docker-compose.yaml
src/pydiverse/pipedag/backend/table/sql.py
src/pydiverse/pipedag/backend/table/util/__init__.py
src/pydiverse/pipedag/backend/table/util/engine_dispatch.py
src/pydiverse/pipedag/backend/table/util/sql_ddl.py
src/pydiverse/pipedag/core/stage.py
tests/test_sql_ddl.py
tests/test_util.py

This PR cleans up how we handle different sql dialects. It introduces a `engine_dispatch` decorator that dispatches to the correct function implementation based on the current engine's dialect. This allows for significantly less nested and more readable code.
I also changed how `DropSchema` with `cascade=True` gets handled for IBM Db2. Instead of manually having to drop everything in the schema before calling `DropSchema`, the `DropSchema` visitor now inspects the schema and creates an sql query that first drops all tables and only then drops the schema.
Finally, I also replaced the `mcr.microsoft.com/mssql/server:2019-latest` docker image with `mcr.microsoft.com/azure-sql-edge`, because the latter also works on Apple Silicon Macs.

Sql refactoring

---

CHANGELOG.rst
src/pydiverse/pipedag/backend/table/base.py
src/pydiverse/pipedag/backend/table/dict.py
src/pydiverse/pipedag/backend/table/sql.py
src/pydiverse/pipedag/backend/table/util/sql_ddl.py
src/pydiverse/pipedag/materialize/container.py
src/pydiverse/pipedag/materialize/util/json.py
tests/test_flows/raw_sql_scripts/mssql/prep/more_tables.sql
tests/test_flows/raw_sql_scripts/mssql_pytsql/prep/more_tables.sql
tests/test_flows/raw_sql_scripts/mssql_pytsql_isolate/prep/more_tables.sql
tests/test_flows/test_raw_sql_pipeline.py
tests/test_indexes.py
tests/util/tasks_library.py

We already had a primary_key parameter to Table constructor, but it was not implemented. And it is non-trivial to get that to work with postgres, mssql, and ibm_db_sa...

Create Primary Keys and Indexes

---

CHANGELOG.rst
docs/reference/config.rst
src/pydiverse/pipedag/backend/table/sql.py
tests/fixtures/instance.py
tests/resources/pipedag.yaml
tests/test_cache/conftest.py
tests/test_cache/test_ignore_fresh_input.py
tests/test_indexes.py
tests/test_materialize.py
tests/util/tasks_library.py

Also removed a few unused imports and emphasized with a comment how instance_id parameterized tests are activated for a file/directory.

Implemented #39: option avoid_drop_create_schema

---

src/pydiverse/pipedag/backend/table/util/sql_ddl.py
tests/test_indexes.py
tests/util/tasks_library.py

We have a bug that primary/index names are not separated per table in many database targets. This PR fixes it by adding table name to index names.

Fix primary key / index with same column on different tables within schema

---

CHANGELOG.rst
src/pydiverse/pipedag/backend/table/base.py
src/pydiverse/pipedag/backend/table/dict.py
src/pydiverse/pipedag/backend/table/sql.py
src/pydiverse/pipedag/backend/table/util/sql_ddl.py
src/pydiverse/pipedag/context/run_context.py
src/pydiverse/pipedag/materialize/core.py
src/pydiverse/pipedag/materialize/store.py
src/pydiverse/pipedag/util/config.py
tests/test_cache/test_basic_cache_invalidation.py
tests/test_materialize.py
tests/util/tasks_library.py

This PR adds a lot of customization for DB2 targets which improve performance:
- lock on table level
- make primary key columns not nullable in the middle of CreateTableAsSelect compilation
- ALIAS instead of VIEWS
...

Speed up performance for DB2

---

src/pydiverse/pipedag/core/flow.py
src/pydiverse/pipedag/core/task.py

This is a potential fix for #34.
This PR would change the way exceptions get logged, such that whenever a task raises an exception, it gets logged at the `ERROR` level. Previously, it would just log that the task failed (at the `WARNING` level) without logging the specific exception.

Log exceptions produced by tasks, even if `fail_fast=False`

---

CHANGELOG.rst
poetry.lock
pyproject.toml
pytest.ini
src/pydiverse/pipedag/backend/table/base.py
src/pydiverse/pipedag/backend/table/sql.py
src/pydiverse/pipedag/backend/table/util/sql_ddl.py
tests/conftest.py
tests/fixtures/instances.py
tests/resources/pipedag.yaml
tests/test_cache/test_ignore_fresh_input.py
tests/test_indexes.py
tests/util/tasks_library.py

DuckDB is quite similar to Postgres, consequently it is quite an easy backend to support.

Add support for DuckDB

---

src/pydiverse/pipedag/backend/lock/database.py
src/pydiverse/pipedag/backend/table/sql.py
src/pydiverse/pipedag/backend/table/sql_hooks.py
src/pydiverse/pipedag/backend/table/util/sql_ddl.py
src/pydiverse/pipedag/backend/table/util/sql_reflection.py

Our issues with IBM DB2 were caused by using `compiler.preparer.quote_identifier` instead of `compiler.preparer.quote`. Unlike `quote`, `quote_identifier` doesn't check if a name should get quoted or not. Because in SQLAlchemy all lowercase identifiers are viewed as case insensitive ([ref](https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Table.params.name)), this resulted in our custom DDL statements interacting incorrectly with SQLAlchemy.

Get rid of `ibm_db_sa_fix_name` hack

---

src/pydiverse/pipedag/core/task.py
src/pydiverse/pipedag/debug/__init__.py
src/pydiverse/pipedag/materialize/core.py
src/pydiverse/pipedag/materialize/debug.py
src/pydiverse/pipedag/materialize/store.py
tests/test_materialize.py
tests/util/tasks_library.py

Add pipedag.debug.materialize_table, a function to ad-hoc materialize a table from a task for interactive debugging
Related issue: #116

Add a function to ad-hoc materialize a table for interactive debugging

---

docs/source/changelog.md
pipedag.yaml
src/pydiverse/pipedag/backend/table/sql/dialects/ibm_db2.py
src/pydiverse/pipedag/backend/table/sql/dialects/postgres.py
src/pydiverse/pipedag/backend/table/sql/sql.py
src/pydiverse/pipedag/materialize/details.py
tests/test_sql_dialect/test_postgres.py

This PR builds on #122.
I moves the Postgres `unlogged` feature to the materialization details.
Also, it refactors some code around the table stores needed for materialization details to reduce code duplication.

Postgres unlogged tables as a materialization detail

---

pipedag.yaml
src/pydiverse/pipedag/backend/table/sql/dialects/ibm_db2.py
tests/fixtures/instances.py
tests/test_cache/test_ignore_cache_function.py
tests/test_compression.py
tests/test_sql_dialect/test_ibm_db2.py

This PR fixes a crash when providing DB2 with no materialization details. It also adds a `ibm_db2_materialization_details` instance and removes the materialization details from the `ibm_db2` instance.

Fix no materialization details

---

docs/source/changelog.md
src/pydiverse/pipedag/backend/table/base.py
tests/test_cache/test_basic_cache_invalidation.py
tests/util/tasks_library.py

The cache validity of a lazy task cannot be judged when the tables output by the task do not provide query strings. This should result in the task being cache invalid which it currently does not. This task fixes this.

Make lazy task output tables which do not provide a query string cache invalid for subsequent reading tasks

---

src/pydiverse/pipedag/materialize/core.py

fixes the link in the docstring for the sphinx docs :)

Update link to table backends

---

src/pydiverse/pipedag/backend/table/cache/parquet.py
tests/test_flows/raw_sql_scripts/mssql/prep/more_tables.sql
tests/test_flows/test_raw_sql_pipeline.py
tests/test_flows/test_sql_text_node.py
tests/test_raw_sql/util.py
tests/test_sql_dialect/test_ibm_db2.py
tests/test_unicode.py

This pull request is supposed to test special character handling with database targets. It is not comprehensive but the first tests using more than ASCII. It already turned out that Microsoft SQL Server is not handling some unicode characters such as λ (U+03BB) well.
The reason that unicode was found as a potential problem source turned out to be a problem in user code. In case you happen to load SQL files into pipedag, beware that `Path(path).read_text()` does not correctly read UTF-8 files on some operating systems. Explicitly specifying the encoding parameter is highly recommended. (see https://github.com/pydiverse/pydiverse.pipedag/blob/main/tests/test_flows/test_raw_sql_pipeline.py#L32)

Add some unicode tests

---

README.md
docs/package/README.md
docs/source/changelog.md
docs/source/database_testing.md
example/run_pipeline.py
example_postgres/run_pipeline.py
pyproject.toml
src/pydiverse/pipedag/backend/table/util/dtype.py
tests/test_table_hooks/test_dtype_sqlalchemy.py

Bug fix which has nothing to do with the release yesterday. But a project figured out problems loading fixpoint columns (i.e. DECIMAL(15,2) in a pandas task). The precision parameter of sa.Numeric was handled identically to sa.Float. However for Float it is in bits and for Numeric it is in decimal places. Nevertheless `isinstance(sa.Float(), sa.Numeric) == True`.

Fix numeric to float

---

src/pydiverse/pipedag/backend/table/sql/dialects/mssql.py

Added the `max_nchars_query_print` option for the `MSSqlTableStore` allowing configuration of the maximum number of characters in a SQL query that are printed to the log

Adding max_nchars_query_print option for MSSqlTableStore

---

docs/source/changelog.md
pyproject.toml
src/pydiverse/pipedag/backend/table/sql/sql.py
src/pydiverse/pipedag/context/run_context.py
tests/test_cache/test_basic_cache_invalidation.py

SQLTableStore, now supports parameters max_concurrent_copy_operations, sqlalchemy_pool_size, sqlalchemy_pool_timeout.
We encountered the situation that the pipeline aborted because a `sa.inspect()` call timed out because the full sqlalchemy connection pool was occupied copying tables between schemas.

Emergency Release 0.7.2: Implemented config for max_copy_operations, pool_size, pool_timeout.

---

docs/source/changelog.md
src/pydiverse/pipedag/backend/table/sql/ddl.py
src/pydiverse/pipedag/backend/table/sql/dialects/duckdb.py
src/pydiverse/pipedag/backend/table/sql/dialects/ibm_db2.py
src/pydiverse/pipedag/backend/table/sql/dialects/mssql.py
src/pydiverse/pipedag/backend/table/sql/dialects/postgres.py
src/pydiverse/pipedag/backend/table/sql/hooks.py
src/pydiverse/pipedag/backend/table/sql/sql.py
src/pydiverse/pipedag/materialize/container.py
tests/test_cache/test_basic_cache_invalidation.py
tests/test_materialize.py

The initial idea of this PR is to add a nullable and non_nullable parameter to pipedag.Table(). It should allow specifying nullability both positive and negative. For most dialects it is beneficial to create an empty table, then set nullability, and finally fill the table.
This PR turned into a somewhat bigger refactoring. DB2 had some create empty table and then fill it logic in DDL code, but if it is not a single dialect, I prefer such complex control in the hook and table store code. Also the generic/specific split of how derived classes can customize the generic algorithm was redesigned.

Support nullable and non_nullable parameters in pipedag.Table() and refactor ddl/table-store/hook logic

---

docs/source/changelog.md
pyproject.toml
src/pydiverse/pipedag/backend/table/sql/dialects/mssql.py

For mssql backend, moved string type changes for index columns after creation of empty table and before filling it. We were not sure at first which one would be faster.

Move primary key generation for mssql backend after completely filling a table.

---

docs/source/changelog.md
pyproject.toml
src/pydiverse/pipedag/backend/lock/database.py
src/pydiverse/pipedag/backend/table/base.py
src/pydiverse/pipedag/backend/table/sql/hooks.py
src/pydiverse/pipedag/backend/table/sql/sql.py
src/pydiverse/pipedag/context/context.py
src/pydiverse/pipedag/util/import_.py
tests/test_table_hooks/test_pandas.py
tests/test_table_hooks/test_pandas_hook.py
tests/test_table_hooks/test_polars.py
tests/util/sql.py
tests/util/tasks_library.py

- Added `replace_hooks` argument for `register_table`. This avoids reliance on import order.
Given hooks are removed from the table store for which the new hook is registered. If the replace_hooks are located in parent classes, they have lower priority anyways. Please, note, that replace_hooks argument is not effective in case the replacement hooks was registered on a subclass of the table store where the new hook is added. 
If `replace_hooks=None`, the new hook is just added to the list of available hooks.
- Added another hook for download of polars Tables (FYI @nicolasmueller )

fix(): add previous_hook_replace argument for register_table

---

docs/source/changelog.md
src/pydiverse/pipedag/backend/table/sql/ddl.py
tests/test_indexes.py
tests/util/tasks_library.py

MSSQL does not allow identifiers longer than 128 characters. 
Similarly, postgres automatically truncates identifiers at 63 characters.
This PR automatically truncates all primary key and index identifiers at 63 characters.

feat(): add truncation of primary keys and indexes

---

docs/source/changelog.md
pipedag.yaml
src/pydiverse/pipedag/backend/table/base.py
src/pydiverse/pipedag/backend/table/dict.py
src/pydiverse/pipedag/backend/table/sql/sql.py
src/pydiverse/pipedag/core/flow.py
src/pydiverse/pipedag/core/task.py
src/pydiverse/pipedag/engine/base.py
src/pydiverse/pipedag/engine/dask.py
src/pydiverse/pipedag/engine/prefect.py
src/pydiverse/pipedag/engine/sequential.py
src/pydiverse/pipedag/materialize/core.py
src/pydiverse/pipedag/materialize/store.py
tests/test_materializing_task.py
tests/test_run_subflow.py

Added `ignore_position_hashes` option to `SQLTableStore`. 
If `True`, the position hashes of tasks are not checked when retrieving the inputs of a task from the cache.
This can prevent caching errors when evaluating subgraphs. 
For this to work a task may never be used more than once per stage.

feat(): Added ignore_position_hash option for SQLTableStore

---

docs/source/changelog.md
pyproject.toml
src/pydiverse/pipedag/backend/table/base.py
src/pydiverse/pipedag/backend/table/dict.py
src/pydiverse/pipedag/backend/table/sql/sql.py
src/pydiverse/pipedag/context/run_context.py
src/pydiverse/pipedag/context/trace_hook.py
src/pydiverse/pipedag/core/flow.py
src/pydiverse/pipedag/core/stage.py
src/pydiverse/pipedag/materialize/container.py
src/pydiverse/pipedag/materialize/core.py
src/pydiverse/pipedag/util/structlog.py
tests/test_materialize.py
tests/util/tasks_library.py

@windiana42 My expectation is that even when using imperative materialization in a task it should stay cache valid if its inputs did not change. In complex cases this can break.
This PR serves as a minimal example:` test_materialize.py::test_imperative_minimal_example`

bug(): Complex tasks using imperative materialization break caching + release `v 0.9.4`

---

docs/source/changelog.md
pixi.lock
pixi.toml
src/pydiverse/pipedag/backend/table/sql/dialects/duckdb.py

There is a speedup mechanism for writing dataframes to duckdb in pipedag which requires access to a raw database connection of duckdb. Previously, this raw connection was opened fresh extracting the duckdb URL from the sqlalchemy engine. Since DuckDB 1.1, this results in an error, because the raw connection is setup differently than the sqlalchemy connection. This PR proposes a fix to get the raw_connection() from the SQLAlchemy engine directly. The raw_connection is used to reference a dataframe from the python scope directly: `INSERT... SELECT * FROM df` where `df` is the variable holding the dataframe

Fix DuckDB 1.1 incompatibility

---

.github/workflows/release.yml

We run `twine check` anyway before.
```
❯ pixi exec -s twine=5.1.1 -- twine check dist/*
Checking dist/pydiverse_pipedag-0.9.8-py3-none-any.whl: ERROR    InvalidDistribution: Metadata is missing required fields: Name, Version.                                   
Make sure the distribution includes the files where those fields are specified, and is using a supported   
Metadata-Version: 1.0, 1.1, 1.2, 2.0, 2.1, 2.2, 2.3.                                                       
❯ pixi exec -s twine=6.1.0 -- twine check dist/*
Checking dist/pydiverse_pipedag-0.9.8-py3-none-any.whl: PASSED
Checking dist/pydiverse_pipedag-0.9.9-py3-none-any.whl: PASSED
Checking dist/pydiverse_pipedag-0.9.8.tar.gz: PASSED
Checking dist/pydiverse_pipedag-0.9.9.tar.gz: PASSED
```

Disable twine check in publish step

---

.github/workflows/test.yml

Currently many CI runs are crashing, because setting up the environment takes almost all of the available time. This PR increases the timeout from 10 minutes to 30.

ci: Increase timeout

---

docker-compose.yaml
docs/source/changelog.md

I suggest using the SQL Server docker image instead of Azure edge:
1. We intend to support SQL Server and only used Azure edge as a proxy for its functionality.
2. Azure edge will be discontinued in October 2025: https://azure.microsoft.com/de-de/updates?id=azure-sql-edge-retirement

ci: Use SQL Server docker image instead of Azure edge

---

src/pydiverse/pipedag/backend/table/sql/dialects/mssql.py

`polars.write_database` uses either `pandas.to_sql` or `adbc` but not `arrow-odbc`.

fix: Correct warning message for polars upload_table

---

docs/source/changelog.md
src/pydiverse/pipedag/context/run_context.py
src/pydiverse/pipedag/core/result.py
src/pydiverse/pipedag/materialize/core.py
tests/test_cache/test_local_table_cache.py

Make it possible to enable writing to the local table cache after the flow has finished when calling `Result.get()`.

feat: Add `write_local_table_cache` to `Result.get()`

---

docs/source/changelog.md
pyproject.toml
src/pydiverse/pipedag/backend/table/sql/dialects/duckdb_parquet.py
src/pydiverse/pipedag/context/context.py
src/pydiverse/pipedag/materialize/store.py

This is necessary for handling multiple configurations (e.g. @input_stage_versions)

Defer initialization of instance_id and fix problem in ParquetTableCache with multi-config code.
