- CHANGELOG.rst
- README.md
> add conda based poetry installation instructions

- README.md
- src/pydiverse/pipedag/core/flow.py
- src/pydiverse/pipedag/core/stage.py
- src/pydiverse/pipedag/core/task.py
- src/pydiverse/pipedag/materialize/core.py
- src/pydiverse/pipedag/materialize/store.py
- src/pydiverse/pipedag/util/__init__.py
- src/pydiverse/pipedag/util/deep_map.py
> Slight cleanups based on another pair of eyes

- docker-compose.yaml
- poetry.lock
- pyproject.toml
- src/pydiverse/pipedag/backend/table/base.py
- src/pydiverse/pipedag/context/run_context.py
- src/pydiverse/pipedag/engine/prefect.py
- src/pydiverse/pipedag/materialize/core.py
- src/pydiverse/pipedag/util/ipc.py
- tests/pipedag.toml
This change implements support for a name parameter to @materialize tasks which makes its way into task names before the Prefect flow is constructed.
It is not a big enough change to release separately and mention it in CHANGELOG.rst.
> Little changes to make life easier working Prefect 1.3

- src/pydiverse/pipedag/context/run_context.py
- src/pydiverse/pipedag/core/flow.py
- src/pydiverse/pipedag/core/result.py
- src/pydiverse/pipedag/materialize/core.py
- src/pydiverse/pipedag/materialize/store.py
- tests/test_flows/test_simple_flow.py
- tests/test_flows/test_source_invalidation.py
Draft solution to #12, will open to merge once some unit tests are added.
> Added source cache invalidation (#12)

- docs/reference/config.rst
- pyproject.toml
- src/pydiverse/pipedag/backend/blob.py
- src/pydiverse/pipedag/backend/lock.py
- src/pydiverse/pipedag/backend/table/base.py
- src/pydiverse/pipedag/backend/table/dict.py
- src/pydiverse/pipedag/backend/table/sql.py
- src/pydiverse/pipedag/context/__init__.py
- src/pydiverse/pipedag/context/context.py
- src/pydiverse/pipedag/context/run_context.py
- src/pydiverse/pipedag/core/flow.py
- src/pydiverse/pipedag/core/result.py
- src/pydiverse/pipedag/materialize/store.py
- src/pydiverse/pipedag/materialize/util/json.py
- src/pydiverse/pipedag/util/__init__.py
- src/pydiverse/pipedag/util/config.py
- src/pydiverse/pipedag/util/deep_merge.py
- tests/test_flows/complex_config_flows/conftest.py
- tests/test_flows/complex_config_flows/pipedag_anchor.yaml
- tests/test_flows/complex_config_flows/test_instance_selection.py
- tests/test_flows/test_flow.py
- tests/test_flows/test_simple_flow.py
- tests/test_flows/test_source_invalidation.py
- tests/test_flows/test_sql_text_node.py
- tests/test_materialize.py
> Cleanups: Config management, LockStateContext, execute_raw_sql

- src/pydiverse/pipedag/backend/table/base.py
- src/pydiverse/pipedag/backend/table/dict.py
- src/pydiverse/pipedag/backend/table/sql.py
- src/pydiverse/pipedag/context/context.py
- src/pydiverse/pipedag/context/run_context.py
- src/pydiverse/pipedag/core/flow.py
- src/pydiverse/pipedag/materialize/container.py
- src/pydiverse/pipedag/materialize/core.py
- src/pydiverse/pipedag/materialize/metadata.py
- src/pydiverse/pipedag/materialize/store.py
- src/pydiverse/pipedag/materialize/util/json.py
This fixes the incorrect behaviour of `flow.run(ignore_fresh_input=True)`.
> Fix cache behaviour (see #22, #23)

- CHANGELOG.rst
- src/pydiverse/pipedag/backend/table/sql.py
- src/pydiverse/pipedag/context/run_context.py
- src/pydiverse/pipedag/materialize/cache.py
- tests/test_util.py
This improves compatibility for pythin 3.9.
> closes #57: replace format_exception with format_exc

- CHANGELOG.rst
- poetry.lock
- src/pydiverse/pipedag/backend/table/sql.py
> Increase tasks.output_json length

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- pytest.ini
- src/pydiverse/pipedag/backend/table/sql.py
- tests/resources/pipedag.yaml
- tests/test_flows/test_ibis.py
> Add support for IBIS as a way to programmatically create SQL (and tests)

- .github/workflows/ci.yml
- CHANGELOG.rst
- poetry.lock
- pyproject.toml
- pytest.ini
- src/pydiverse/pipedag/backend/table/sql.py
- tests/conftest.py
- tests/resources/pipedag.yaml
- tests/test_flows/test_ibis.py
- tests/test_flows/test_polars.py
> Add polars and tidypolars support for pipedag

- .github/workflows/ci.yml
- CHANGELOG.rst
- README.md
- poetry.lock
- pyproject.toml
- src/pydiverse/pipedag/backend/table/sql.py
- src/pydiverse/pipedag/backend/table/util/sql_ddl.py
- src/pydiverse/pipedag/materialize/container.py
- src/pydiverse/pipedag/materialize/util/json.py
- tests/test_flows/complex_config_flows/test_instance_selection.py
- tests/test_flows/test_example.py
- tests/test_flows/test_flow.py
- tests/test_flows/test_ibis.py
- tests/test_flows/test_pdtransform.py
- tests/test_flows/test_source_invalidation.py
- tests/test_flows/test_sql_text_node.py
- tests/test_materialize.py
- tests/util/tasks_library.py
> Pandas <-> SQL type mapping and chunksize=100k

- CHANGELOG.rst
- src/pydiverse/pipedag/backend/table/base.py
- src/pydiverse/pipedag/backend/table/dict.py
- src/pydiverse/pipedag/backend/table/sql.py
- src/pydiverse/pipedag/backend/table/util/sql_ddl.py
- src/pydiverse/pipedag/materialize/store.py
- src/pydiverse/pipedag/util/naming.py
- tests/test_cache/test_basic_cache_invalidation.py
- tests/test_flows/test_sql_text_node.py
> fix ibm_db_sa bug when copying dataframes from cache: uppercase table names by default

- .github/workflows/ci.yml
- CHANGELOG.rst
- README.md
- docs/package/README.md
- docs/reference/config.rst
- example/pipedag.yaml
- example/run_pipeline.py
- poetry.lock
- pyproject.toml
- src/pydiverse/pipedag/backend/__init__.py
- src/pydiverse/pipedag/backend/blob.py
- src/pydiverse/pipedag/backend/table/base.py
- src/pydiverse/pipedag/backend/table/dict.py
- src/pydiverse/pipedag/backend/table/sql.py
- src/pydiverse/pipedag/backend/table/util/pandas.py
- src/pydiverse/pipedag/backend/table_cache.py
- src/pydiverse/pipedag/context/context.py
- src/pydiverse/pipedag/materialize/cache.py
- src/pydiverse/pipedag/materialize/core.py
- src/pydiverse/pipedag/materialize/store.py
- src/pydiverse/pipedag/util/config.py
- tests/resources/pipedag.yaml
- tests/test_cache/test_local_table_cache.py
- tests/test_flows/complex_config_flows/pipedag_anchor.yaml
- tests/test_flows/complex_config_flows/pipedag_complex.yaml
- tests/test_flows/complex_config_flows/test_instance_selection.py
- tests/test_flows/test_example.py
- tests/test_flows/test_flow.py
- tests/test_flows/test_source_invalidation.py
> Implement local table cache that stores inputs/outputs of dataframe tasks in parquet

- poetry.lock
- pyproject.toml
- src/pydiverse/pipedag/util/ipc.py
Addresses PR #51 using [Fernet](https://cryptography.io/en/latest/fernet/#fernet-symmetric-encryption).
> Encrypt and authenticate IPC Server + Client communication

- .github/PULL_REQUEST_TEMPLATE.md
- docs/source/changelog.md
> Update PR template

- .github/workflows/tests.yml
- docs/source/changelog.md
- src/pydiverse/pipedag/backend/table/sql/ddl.py
- src/pydiverse/pipedag/backend/table/sql/reflection.py
- src/pydiverse/pipedag/backend/table/sql/sql.py
- src/pydiverse/pipedag/materialize/container.py
- tests/test_sql_dialect/scripts/simple_nicknames.sql
- tests/test_sql_dialect/test_ibm_db2.py
Add support for dropping DB2 nicknames.
> Drop DB2 nicknames

- README.md
- docs/source/changelog.md
This should also be possible without using pip directly, but I could not get it to work using only poetry.
> Instructions for getting pyodbc to run on OS X

- poetry.lock
- pyproject.toml
- src/pydiverse/pipedag/backend/table/sql/hooks.py
- src/pydiverse/pipedag/backend/table/sql/sql.py
- tests/test_table_hooks/test_pandas.py
LazyFrame write_json was renamed serialize.
> Fix problems in tests after updating dependencies

- poetry.lock
- pyproject.toml
> make pytz and pytzdata optional dependencies

- README.md
- docs/package/README.md
- docs/source/changelog.md
- docs/source/index.md
- docs/source/reference/config.md
- docs/source/table_backends.md
- pyproject.toml
- src/pydiverse/pipedag/materialize/core.py
> Documented input_type options and concepts for future enhancements.

- README.md
- docs/package/README.md
- docs/source/quickstart.md
- example/run_pipeline.py
- src/pydiverse/pipedag/core/config.py
> Fix duckdb example documentation

- src/pydiverse/pipedag/backend/table/sql/ddl.py
- tests/test_flows/complex_config_flows/test_instance_selection.py
These DDL extensions were developed with another cloned repo and backported here.
> Smallish DDL extension

- README.md
- docs/package/README.md
- docs/source/changelog.md
- docs/source/database_testing.md
- docs/source/reference/config.md
- example/run_pipeline.py
- example_postgres/pipedag.yaml
- pipedag.yaml
- src/pydiverse/pipedag/context/context.py
- src/pydiverse/pipedag/core/config.py
- src/pydiverse/pipedag/core/flow.py
- tests/test_core.py
- tests/test_flows/complex_config_flows/pipedag_anchor.yaml
- tests/test_flows/complex_config_flows/pipedag_complex.yaml
- tests/test_table_hooks/test_pandas.py
> Disable kroki links by default.

- docs/source/changelog.md
- src/pydiverse/pipedag/context/run_context.py
- src/pydiverse/pipedag/materialize/container.py
- tests/test_table_hooks/test_sql_table_reference.py
Fix bug where a table could not be created if an external table with the same name is loaded in the same stage.
> Fix duplicate table bug

- docs/source/changelog.md
- src/pydiverse/pipedag/backend/table/sql/dialects/duckdb.py
- src/pydiverse/pipedag/backend/table/sql/dialects/ibm_db2.py
- src/pydiverse/pipedag/backend/table/sql/dialects/mssql.py
- src/pydiverse/pipedag/backend/table/sql/sql.py
> Setting the isolation level for MSSQL table store to READ UNCOMMITED

- docs/source/changelog.md
- src/pydiverse/pipedag/backend/table/sql/hooks.py
> Do not require connectorx for polars dematerialization

- docs/source/changelog.md
- src/pydiverse/pipedag/backend/table/sql/hooks.py
- tests/test_table_hooks/test_pandas.py
Add an easy way to customize upload and download behavior of pandas and polars tables to/from the table store
> feat(): add upload_table and download_table functions to PandasTableHook

- docs/source/changelog.md
- pyproject.toml
- src/pydiverse/pipedag/backend/table/sql/dialects/postgres.py
- tests/test_materialize.py
> Fix primary_key generation when writing pandas dataframe to postgres database

- docs/source/changelog.md
- pyproject.toml
> feat(): Release 0.9.7

- docs/source/changelog.md
- src/pydiverse/pipedag/core/flow.py
- src/pydiverse/pipedag/core/task.py
- src/pydiverse/pipedag/engine/base.py
- src/pydiverse/pipedag/engine/dask.py
- src/pydiverse/pipedag/engine/prefect.py
- src/pydiverse/pipedag/engine/sequential.py
- tests/test_inputs.py
The inputs feature did not work if the depended tasks were not previously executed.
This PR should fix this
> fix(): bugfix for flow.run(inputs)

- pyproject.toml
> release 0.9.8

- docs/source/changelog.md
- pixi.lock
- pixi.toml
I encountered this problem locally.
> chore: Fix numpy import issues
